browser.name=chrome
browser.version=128.0

frontend.url=http://frontend:4000
backend.url=http://app:1111/api/v1/
moon.host=http://selenoid:4444/wd/hub

postgres.jdbcUrl=jdbc:postgresql://database:5432/playground
postgres.username=postgres
postgres.password=postgres

remote.enabled=true